version: "3.9"
volumes:
  php-fpm-socket:
  db-store:
  psysh-store:
services:
  app:
    depends_on:
      - web
      - db
      - redis
      - mail
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}
      - POSTGRES_USER=${DB_USER:-phper}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
      - POSTGRES_DB=${DB_NAME:-laravel_local}

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend

  # db:
  #   build:
  #     context: .
  #     dockerfile: ./infra/docker/mysql/Dockerfile
  #   hostname: mysql
  #   ports:
  #     - target: 3306
  #       published: ${DB_PORT:-3306}
  #       protocol: tcp
  #       mode: host
  #   volumes:
  #     - type: volume
  #       source: db-store
  #       target: /var/lib/mysql
  #       volume:
  #         nocopy: true
  #   environment:
  #     - MYSQL_DATABASE=${DB_NAME:-laravel_local}
  #     - MYSQL_USER=${DB_USER:-phper}
  #     - MYSQL_PASSWORD=${DB_PASS:-secret}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}

  db:
    image: postgres:12.2-alpine
    hostname: pgsql
    ports:
      - target: 5432
        published: ${DB_PORT:-5432}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/postgresql
        volume:
          nocopy: true
    environment:
      POSTGRES_USER: ${DB_USER:-phper}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_NAME:-laravel_local}

  redis:
    image: "redis:latest"
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  mail:
    image: mailhog/mailhog
    container_name: mail
    hostname: mailhog
    ports:
      - 1025:1025
      - 8025:8025
